{
 "title": "HF Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "prometheus" },
   {
    "name": "channel",
    "label": "Channel Name",
    "query": "label_values(ledger_blockchain_height,channel)"
   },
   {
    "name": "cc_name",
    "label": "Chaincode Name",
    "query": "label_values(chaincode_launch_duration_sum,chaincode)"
   },
   {
    "name": "couchdb_db",
    "label": "Peer CouchDB DB Name",
    "query": "label_values(couchdb_processing_time_sum,database)"
   }
  ]
 },
 "panels": [
  { "title": "Endorsement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "endorser_proposal_duration (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(endorser_proposal_duration_sum{chaincode=\"$cc_name\"}[1m])/rate(endorser_proposal_duration_count{chaincode=\"$cc_name\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "endorser_proposal_duration_count (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(endorser_proposal_duration_count{channel=\"$channel\",chaincode=\"$cc_name\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "blockcutter_block_fill_duration (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "channel",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(blockcutter_block_fill_duration_sum{channel=\"$channel\"}[1m])) / sum by (service) (rate(blockcutter_block_fill_duration_count{channel=\"$channel\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ledger_blockchain_height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Block Height" }
   ],
   "targets": [
    {
     "expr": "ledger_blockchain_height{channel=\"$channel\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ledger_transaction_count (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(ledger_transaction_count{channel=\"$channel\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}